[package]
name = "ms-oforms"
version = "0.2.0"
authors = ["Xiphoseer"]
edition = "2018"
description = "Parser and Datastructures for [MS-OFORMS]"
license = "MIT"
repository = "https://github.com/xiphoseer/rust-ms-oforms"

[dependencies]
bitflags = "1.0"
nom-methods = "0.1"
nom = "4.2"
num-traits = "0.2"
num-derive = "0.2"
encoding = "0.2"
